name: Lint
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    timeout-minutes: 10
    name: Validate Code
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: install
        uses: ./.github/actions/install

      - name: SetUp pre-commit env from cache
        id: pre-commit-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit=${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: poetry run pre-commit run --color=always --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
