name: Test CI

on:
  push:
    branches:
    - main

  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: install
      uses: ./.github/actions/install

    - name: Test with pytest
      run: make test

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage.xml
